apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ira-controller.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
    {{- include "ira-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "ira-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        {{- include "ira-controller.selectorLabels" . | nindent 8 }}
        {{- with .Values.controllerManager.manager.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        {{- if .Values.controllerManager.manager.useCertManager }}
        - --generate-cert
        {{- end }}
        {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /ira-controller
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- with .Values.controllerManager.manager.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.controllerManager.manager.containerSecurityContext }}
        securityContext: {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "ira-controller.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      {{- with .Values.controllerManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.controllerManager.priorityClassName }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert