{{- if .Values.webhookService.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ira-controller.fullname" . }}-serving-cert
  labels:
    {{- include "ira-controller.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "ira-controller.fullname" . }}-webhook-service.{{ .Release.Namespace}}.svc'
  - '{{ include "ira-controller.fullname" . }}-webhook-service.{{ .Release.Namespace}}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "ira-controller.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert
{{- end }}