apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ira-controller.fullname" . }}-controller-manager
  labels:
    {{- include "ira-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}