apiVersion: v1
kind: Service
metadata:
  name: {{ include "ira-controller.fullname" . }}-webhook-service
  labels:
    {{- include "ira-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
    {{- include "ira-controller.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 4 }}
